package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"

	climanager "github.com/example/p2p-dpos/cli"
	"github.com/example/p2p-dpos/config"
	"github.com/example/p2p-dpos/node"
	"github.com/urfave/cli/v2"
	"go.uber.org/zap"
)

func main() {
	// Create logger
	logger, err := zap.NewProduction()
	if err != nil {
		panic(fmt.Sprintf("failed to create logger: %v", err))
	}
	defer logger.Sync()

	// Create CLI app
	app := &cli.App{
		Name:  "p2p-dpos",
		Usage: "P2P Blockchain with Delegated Proof of Stake",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "datadir",
				Value: "./data",
				Usage: "data directory for blockchain storage",
			},
			&cli.StringFlag{
				Name:  "loglevel",
				Value: "info",
				Usage: "log level: debug, info, warn, error",
			},
		},
		Commands: []*cli.Command{
			{
				Name:  "start",
				Usage: "start a blockchain node",
				Flags: []cli.Flag{
					&cli.Uint64Flag{
						Name:  "port",
						Value: 0,
						Usage: "port to listen on (0 for random)",
					},
					&cli.StringSliceFlag{
						Name:  "bootstrap",
						Usage: "bootstrap peer addresses (multiaddr format)",
					},
					&cli.Uint64Flag{
						Name:  "initial-balance",
						Value: 1000,
						Usage: "initial balance for this node",
					},
				},
				Action: func(c *cli.Context) error {
					return cmdStart(c, logger)
				},
			},
			{
				Name:  "interactive",
				Usage: "start node in interactive mode",
				Flags: []cli.Flag{
					&cli.Uint64Flag{
						Name:  "initial-balance",
						Value: 1000,
						Usage: "initial balance for this node",
					},
				},
				Action: func(c *cli.Context) error {
					return cmdInteractive(c, logger)
				},
			},
		},
	}

	if err := app.Run(os.Args); err != nil {
		logger.Fatal("app error", zap.Error(err))
	}
}

func cmdStart(c *cli.Context, logger *zap.Logger) error {
	cfg := config.DefaultConfig(c.String("datadir"))
	cfg.LogLevel = c.String("loglevel")

	// Set initial balance
	pubKey := "" // Will be generated by node
	cfg.InitialBalances[pubKey] = c.Uint64("initial-balance")

	// Create and start node
	n, err := node.NewNode(cfg, logger)
	if err != nil {
		return fmt.Errorf("failed to create node: %w", err)
	}

	if err := n.Start(); err != nil {
		return fmt.Errorf("failed to start node: %w", err)
	}

	logger.Info("node started successfully")

	// Wait for interrupt
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, syscall.SIGINT, syscall.SIGTERM)
	<-sigChan

	logger.Info("shutdown signal received")
	return n.Stop()
}

func cmdInteractive(c *cli.Context, logger *zap.Logger) error {
	cfg := config.DefaultConfig("./data")
	cfg.LogLevel = c.String("loglevel")

	// Create node
	n, err := node.NewNode(cfg, logger)
	if err != nil {
		return fmt.Errorf("failed to create node: %w", err)
	}

	if err := n.Start(); err != nil {
		return fmt.Errorf("failed to start node: %w", err)
	}

	// Set initial balance
	state := n.GetState()
	state.Mu.Lock()
	state.Balances[n.GetKeypair().PublicKeyHex()] = c.Uint64("initial-balance")
	state.Mu.Unlock()

	logger.Info("node started in interactive mode")
	fmt.Printf("Your public key (peer ID): %s\n", n.GetKeypair().PublicKeyHex())
	fmt.Printf("Initial balance: %d tokens\n", c.Uint64("initial-balance"))
	fmt.Println("\nAvailable commands:")
	fmt.Println("  status              - show node status")
	fmt.Println("  balance [account]   - show account balance")
	fmt.Println("  validators          - list validators")
	fmt.Println("  peers               - show connected peers")
	fmt.Println("  register-validator  - register as validator")
	fmt.Println("  transfer --to <id> --amount <n> - transfer tokens")
	fmt.Println("  delegate --validator <id> --amount <n> - delegate tokens")
	fmt.Println("  help <command>      - show command help")
	fmt.Println("  exit                - stop node")

	// Interactive REPL
	for {
		fmt.Print("\n> ")
		var input string
		_, _ = fmt.Scanln(&input)

		if input == "exit" {
			break
		}

		// Handle commands
		args := []string{"p2p-dpos", input}
		cmdCli := &cli.App{
			Commands: climanager.Commands(n),
		}
		if err := cmdCli.Run(args); err != nil {
			fmt.Printf("Error: %v\n", err)
		}
	}

	return n.Stop()
}
